package com.example.tasks.DataManager;

import java.util.List;

public class Assignment {
    public List<Integer> WhoCanSee; // list of work positions who can see if not administrator
    public String TaskName; // ekstruder + ime
    public String TaskDescription; // razmeri
    public float Weight; // kilogrami
    public List<Integer> ProportionId;
    public boolean IsDone;
    public String DoneByUserId;

    // id autogenerated

    // to do
}
